version: "3.8"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  consul:
    image: hashicorp/consul
    ports:
      - "8500:8500"

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - "zookeeper"
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "
        job-service-event-channel:1:1,
        cleaned-data-event-channel:1:1,
        labeled-data-event-channel:1:1,
        aligned-data-event-channel:1:1,
        manager-informer-event-channel:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Applications

  dim:
    build: ./DataIntegrationManager
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILE=default
    depends_on:
      - "consul"
      - "dimdb"

  dis:
    build: ./DataIntegrationStorage
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILE=default
    depends_on:
      - "consul"
      - "disdb"

  dc:
    build: ./data-cleaner
    depends_on:
      - "kafka"

  dl:
    build: ./data-labeler
    depends_on:
      - "kafka"

  solr:
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - test

  tss:
    build: ./TableStorageService
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILE=default
    depends_on:
      - "consul"
      - "solr"

  copywritergpt:
    build: ./CopywriterGPT
    ports:
      - "8090:8080"
    environment:
      - SPRING_PROFILE=default
    depends_on:
      - "consul"

  dimdb:
    image: postgres
    volumes:
      - "$PWD/postgres:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dimdb
    depends_on:
      - "consul"

  disdb:
    image: postgres
    volumes:
      - "$PWD/postgres:/docker-entrypoint-initdb.d"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: disdb
    depends_on:
      - "consul"

  copywritergptdb:
    image: postgres
    volumes:
      - "$PWD/postgres:/docker-entrypoint-initdb.d"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: copywritergptdb
    depends_on:
      - "consul"

volumes:
  data: