version: "3.8"

services:

  consul:
    image: hashicorp/consul
    ports:
      - "8500:8500"

  tss:
    build: .
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILE=default
      - WAREHOUSE_TECHNOLOGY=CLICKHOUSE
    depends_on:
      - "consul"

  tssdb:
    image: postgres
    volumes:
      - "$PWD/postgres:/docker-entrypoint-initdb.d"
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tssdb
    depends_on:
      - "consul"

  datawarehouse-db:
    image: yandex/clickhouse-server:21.1.2.15
    container_name: datawarehouse-db
    ports:
      - 8123:8123
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
